# Solarized Dark for Alacritty
[colors.primary]
background = "#002b36" # base03
foreground = "#839496" # base0

[colors.cursor]
text = "#002b36"   # base03
cursor = "#839496" # base0

[colors.selection]
text = "#002b36"       # base03
background = "#073642" # base02

[colors.normal]
black = "#073642"   # base02
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"   # base2

[colors.bright]
black = "#002b36"   # base03
red = "#cb4b16"     # orange
green = "#586e75"   # base01
yellow = "#657b83"  # base00
blue = "#839496"    # base0
magenta = "#6c71c4" # violet
cyan = "#93a1a1"    # base1
white = "#fdf6e3"   # base3
