# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
  table:
    showSeparator: true
    compact: false
  colors:
    text:
      primary: "#ffffff"
      secondary: "#c6c6c6"
      inverted: "#303030"
      faint: "#8a8a8a"
      warning: "#800000"
      success: "#008000"
    background:
      selected: "#808080"
    border:
      primary: "#808080"
      secondary: "#c0c0c0"
      faint: "#000000"
    inline:
      icons:
        newcontributor: "077"
        contributor: "075"
        collaborator: "178"
        member: "178"
        owner: "178"
        unknownrole: "178"
pager:
  diff: "delta"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
