[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 1

# import solarized_dark theme
import = ["~/.config/alacritty/colors/solarized_dark.toml"]

# recommended if blue/magenta looked “too bright” when bold:
# draw_bold_text_with_bright_colors = false

[colors]
draw_bold_text_with_bright_colors = false
# end experiments from gpt

[env]
COLORTERM = "truecolor"

[font]
size = 12.0
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { key = "Return", action = "ToggleFullscreen", mods = "Alt" },
  { key = "F", action = "ToggleSimpleFullscreen", mods = "Command|Control" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
