[general]
# import theme
import = ["~/.config/alacritty/colors/catppuccin-mocha.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 1

[env]
COLORTERM = "truecolor"

[font]
size = 12.0
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGMDZ Nerd Font", style = "BoldItalic" }

[window]
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Return", action = "ToggleFullscreen", mods = "Alt" },
  { key = "F", action = "ToggleSimpleFullscreen", mods = "Command|Control" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
